/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 CB_default.glb -t
*/

import * as THREE from "three";
import {useFrame} from "@react-three/fiber"
import { useGLTF, } from "@react-three/drei";
import { GLTF } from "three-stdlib";


type GLTFResult = GLTF & {
  nodes: {
    AK_default: THREE.Mesh;
  };
  materials: {
    AK_default: THREE.MeshStandardMaterial;
  };
};

export default function Player2(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "./models/settleglb/AK_default.glb"
  ) as GLTFResult;

	useFrame((state, delta)=> {
		
	})
  return (
    <group
      {...props}
      dispose={null}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[4, 4, 4]}
    >
      <mesh
        geometry={nodes.AK_default.geometry}
        material={materials.AK_default}
      />
    </group>
  );
}
